version: '3'
services:
  django-community:
    container_name: django-community
    image: django_community_image
    build:
      context: .
    ports:
      - 10000:10000
    restart: always
    volumes:
      - ./community/media:/app/community/media
      - ./community/db.sqlite3:/app/community/db.sqlite3
